### PR TITLE
Refactor check_is_article_published() from article provider and move …

### PR DESCRIPTION
**Pull request by gnott**
…to lax_provider.

### CODE REVIEW

**Comment by gnott** [comment]
Travis did not want to complete the build, so I tried an bunch of combinations. Upgrading pyOpenSSL==16.0.0 to pyOpenSSL==16.2.0 (https://github.com/pyca/pyopenssl/issues/525) seems to have done it, as well it does not need sudo on travis.

Considering ``requirements.txt`` changed, I think this is ok, but would you like to confirm please @giorgiosironi ?

**Comment by giorgiosironi** [comment]
Minor upgrade, seems no problem to me. I wonder why it started failing now

**Comment by giorgiosironi** [comment]
We need to merge this as it contains the fix for builds that started failing on Travis - seems a change in the environment there as failures happened also on `develop`.

**Comment by gnott** [comment]
I think travis tests started failing due to their recent migration over to trusty from precise, or some complications with Google Compute Engine. I read the specific errors and tried to diagnose in issues in the boto and pyOpenSSL projects until I found a tweak to make it happy.

**Pull request merged**
