### PR TITLE
Update elifetools version is use, and also elifecrossref and …

### PR DESCRIPTION
**Pull request by gnott**
… elifearticle.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Thinking: can we automate this update like in https://alfred.elifesciences.org/job/dependencies-elife-bot-update-elife-poa-xml-generation/
What's the most common use case?
- update a single one of these 3 projects
- update a subset of them
- update all 3 together
And when should we do it (the automated opening of this PR)?
- when there is a new `master` commit on one of these 3 project
- only when some of them have a new `master` commit, not for all 3
- every day at 10 AM
- every week

**Comment by gnott** [comment]
We're not committing to master branch on any of these projects on a regular basis, not that we could not do that.

elifetools may get updated on its own. elifearticle and elifecrossref are closely tied together, and they would probably get updated at the same time to the latest version if any new commits happened on them.

In this case, I tested the elifecrossref project with the latest elifetools and elifearticle separately so I could be sure the test cases passed. I didn't expect them not to pass since the changes were non-breaking, but you never know.

The commit to master branch might be the best option to automatically update projects and then run tests to be sure it doesn't break anything.

**Comment by gnott** [comment]
I will merge this PR so we can get the elifetools rewrites into production.

**Comment by giorgiosironi** [comment]
No blockers on this PR.

> We're not committing to master branch on any of these projects on a regular basis

Is it because elife-bot follows their `develop` branches instead (if they exist for some of them)? Same reasoning stands, but tracking their `develop` branches rather than `master` if we update from them. But of course if we can merge to `master` on passing tests, it's safer to avoid accidentally importing versions that are red.

> elifetools may get updated on its own.

I'll start from that one and do the same routine that opens PRs like https://github.com/elifesciences/bot-lax-adaptor/pull/350

In that case, the update is triggered when a new `develop` version passes the tests: 
https://github.com/elifesciences/elife-tools/blob/develop/Jenkinsfile#L10-L15
but there is no automated merge in `master`. It's a "bit of both" solution.

**Pull request merged**
