### PR TITLE
Add exact to update-dependencies.sh args

### PR DESCRIPTION
**Pull request by gnott**
A failure of `dependencies-elife-bot-update-dependency` pipeline, I think I've tracked it down to where this Jenkinsfile needs the third argument `exact` to be added, @lsh-0 what do you think please?

### CODE REVIEW

**Comment by lsh-0** [comment]
taking a look, that arg should be optional ...

**Comment by lsh-0** [comment]
I'm running the command locally, but from the output this kinda looks like the error:

```
⠋[0m Installing...[K
[K[?25hTraceback (most recent call last):
[2022-04-22T01:19:48.157Z]   File "/usr/local/bin/pipenv", line 8, in <module>
[2022-04-22T01:19:48.157Z]     sys.exit(cli())
[2022-04-22T01:19:48.158Z]   File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 1128, in __call__
[2022-04-22T01:19:48.158Z]     return self.main(*args, **kwargs)
[2022-04-22T01:19:48.158Z]   File "/usr/local/lib/python3.6/dist-packages/pipenv/cli/options.py", line 56, in main
[2022-04-22T01:19:48.158Z]     return super().main(*args, **kwargs, windows_expand_args=False)
[2022-04-22T01:19:48.158Z]   File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 1053, in main
[2022-04-22T01:19:48.158Z]     rv = self.invoke(ctx)
[2022-04-22T01:19:48.158Z]   File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 1659, in invoke
[2022-04-22T01:19:48.158Z]     return _process_result(sub_ctx.command.invoke(sub_ctx))
[2022-04-22T01:19:48.158Z]   File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 1395, in invoke
[2022-04-22T01:19:48.158Z]     return ctx.invoke(self.callback, **ctx.params)
[2022-04-22T01:19:48.158Z]   File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 754, in invoke
[2022-04-22T01:19:48.158Z]     return __callback(*args, **kwargs)
[2022-04-22T01:19:48.158Z]   File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
[2022-04-22T01:19:48.158Z]     return ctx.invoke(f, obj, *args, **kwargs)
[2022-04-22T01:19:48.158Z]   File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 754, in invoke
[2022-04-22T01:19:48.158Z]     return __callback(*args, **kwargs)
[2022-04-22T01:19:48.158Z]   File "/usr/local/lib/python3.6/dist-packages/pipenv/cli/command.py", line 241, in install
[2022-04-22T01:19:48.158Z]     site_packages=state.site_packages,
[2022-04-22T01:19:48.158Z]   File "/usr/local/lib/python3.6/dist-packages/pipenv/core.py", line 2142, in do_install
[2022-04-22T01:19:48.158Z]     pkg_requirement = Requirement.from_line(pkg_line)
[2022-04-22T01:19:48.158Z]   File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/requirementslib/models/requirements.py", line 2672, in from_line
[2022-04-22T01:19:48.158Z]     if isinstance(line, pip_shims.shims.InstallRequirement):
[2022-04-22T01:19:48.158Z]   File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/pip_shims/shims.py", line 61, in __getattr__
[2022-04-22T01:19:48.158Z]     return locations[args[0]].shim()
[2022-04-22T01:19:48.158Z]   File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/pip_shims/models.py", line 737, in shim
[2022-04-22T01:19:48.158Z]     result = self.traverse(top_path)
[2022-04-22T01:19:48.158Z]   File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/pip_shims/models.py", line 729, in traverse
[2022-04-22T01:19:48.158Z]     result = shim.shim()
[2022-04-22T01:19:48.158Z]   File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/pip_shims/models.py", line 577, in shim
[2022-04-22T01:19:48.158Z]     return self.shim_class(imported, self.name_to_import)
[2022-04-22T01:19:48.158Z]   File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/pip_shims/models.py", line 519, in shim_class
[2022-04-22T01:19:48.158Z]     imported, result = self._shim_parent(imported, attribute_name)
[2022-04-22T01:19:48.158Z]   File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/pip_shims/models.py", line 503, in _shim_parent
[2022-04-22T01:19:48.158Z]     result = self._shim_base(imported, attribute_name)
[2022-04-22T01:19:48.158Z]   File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/pip_shims/models.py", line 492, in _shim_base
[2022-04-22T01:19:48.158Z]     return self._apply_aliases(imported, result)
[2022-04-22T01:19:48.158Z]   File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/pip_shims/models.py", line 497, in _apply_aliases
[2022-04-22T01:19:48.158Z]     target = apply_alias(imported, target, *alias_list)
[2022-04-22T01:19:48.158Z]   File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/pip_shims/utils.py", line 326, in apply_alias
[2022-04-22T01:19:48.158Z]     setattr(target, alias, alias_value)
[2022-04-22T01:19:48.158Z] AttributeError: 'NoneType' object has no attribute 'ensure_build_location'
[2022-04-22T01:19:48.158Z] [0m
[2022-04-22T01:19:48.158Z] exception while executing task 'cmd': 2
```

some Pipenv error

**Comment by lsh-0** [comment]
worked locally so I'm giving the build a kick

**Comment by gnott** [comment]
I was cheating from https://github.com/elifesciences/bot-lax-adaptor/blob/develop/Jenkinsfile.update-dependency to use `exact` but I guess the default is `semver` if not specified?

So I guess `ensure_build_location` is the real error, I have fewer ideas about that one...

**Comment by lsh-0** [comment]
> So I guess ensure_build_location is the real error, I have fewer ideas about that one...

same, not sure. I'll dig deeper if it fails again in the same way.

> I guess the default is semver if not specified?

correct. It's either 'semver' (default) or 'exact' and the result is either `~=0.13.0` (semver) or `==0.13.0` in the `Pipfile`. I guess it's personal preference but I stuck with 'semver' because that is what it was doing before.

**Comment by lsh-0** [comment]
hrm, failed again, same way. I'll take a closer look at this today, probably in an hour or two if that's ok.

**Comment by gnott** [comment]
Much appreciated, it's no rush, I'm not blocked as long as the new `elifecleaner` version can get in some time next week.

**Comment by lsh-0** [comment]
I'm on 2022.1.8 and it works for me, but Pipenv has a recent update:

Screenshot at 2022-04-22 11-25-58

**Comment by lsh-0** [comment]
I'm giving this change a shot: 
https://github.com/elifesciences/update-python-dependencies/commit/74492c71bd114ebf4d35e1ea907b9a28eec6cc5f

I'm also not sure invoking it with 'sh' is useful.

**Comment by gnott** [comment]
I noticed another different, not sure if it matters, added an `sh` before `sh "./update-dependencies.sh ${params.package} ${params.tag}"` in this PR, although if that doesn't look right this PR we can eventually close since I may be further down the wrong path.

**Comment by lsh-0** [comment]
ok, that appears to have fixed the problem.

**Comment by lsh-0** [comment]
blast, it looks like it added pipenv to the list of requirements:
Screenshot at 2022-04-22 11-40-14

should be harmless for now but I'd hold off on merging that PR until I come up with something a bit better.

**Comment by lsh-0** [comment]
better fix: https://github.com/elifesciences/builder-base-formula/pull/347

**Comment by lsh-0** [comment]
that looks better: https://github.com/elifesciences/elife-bot/pull/1469/files

**Comment by gnott** [comment]
I agree, you've done it I think, I will merge pr #1469 because it's green and good.

**Comment by gnott** [comment]
In summary, I'm supposing the `pipenv` version was the problem, some bug in a newer version of it? I'll close this PR now, thanks  @lsh-0!

**Comment by lsh-0** [comment]
that's my conclusion too.

**Pull request closed without merging**
