### PR TITLE
WIP Elpp 2047

### PR DESCRIPTION
**Pull request by Jenniferstrej**
Placeholder for PDF covers e-mail solution.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Definitely blocked until the personalized-covers project has a formula and runs in the various environments (they didn't exactly give us a priority to do that however).

**Comment by Jenniferstrej** [comment]
Settings to be added to the environments are mentioned on settings-example file
+    pdf_cover_generator = "http://localhost:8082/personalcover/"
+    pdf_cover_landing_page = "http://localhost:8082/personalcover/options"

Anything else you need before I merge this @giorgiosironi ?
Any observations @gnott ?

**Comment by Jenniferstrej** [comment]
Actually I should change the examples to ones that are more similar to the URL pattern now. 1 sec

**Comment by gnott** [comment]
If any exception is raised during the Generate PDF Covers, does that mean it will permanently fail the workflow and not continue with any of the following activities in the workflow? Is there a case where the activity should be retried before permanently failing?

**Comment by Jenniferstrej** [comment]
@gnott - currently the endpoint that I call to generate the covers doesn't return anything but 500 when there is an error so it makes it a little difficult to identify when to retry or not. I have been talking to the guys that built the app to enhance it. I am planning to merge this now and we can see how many errors we get on end2end that we can expect and then take any action from there. 

A small change I will do to make it not harmful to anything else is putting this activity as the last one on the PostPerfectPublication.

**Comment by gnott** [comment]
As the last activity that's a good plan for any minimal impact :+1:

**Pull request merged**
