### PR TITLE
ELPP-3150 Removing ResizeImages

### PR DESCRIPTION
**Pull request by giorgiosironi**
The resized images are not used anymore, as the full resolution image (.tif or .jpg) is favored by IIIF and Lens.

There was also a deprecated workflow not updated for 2.0, which I would remove in the same way.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Fixed the test, whose deletion I forgot to commit

**Comment by gnott** [comment]
Tests are passing I see. I approve, with a suggestion to delete the https://github.com/elifesciences/elife-bot/blob/develop/formats.yaml file.

**Comment by giorgiosironi** [comment]
Good catch, removed that as there are no references to it left waiting for the tests to pass again and I'll merge.

**Comment by giorgiosironi** [comment]
Looks like the other activity `ConvertImagesToJPG` doesn't convert all images to JPG:
https://ci--alfred.elifesciences.org/job/test-elife-bot/318/consoleFull
```
2017-09-15 11:36:59     484815 elife-3767122276026901222-fig1-figsupp1-v1-download.jpg
2017-09-15 11:36:59     484815 elife-3767122276026901222-fig1-figsupp1-v1.jpg
2017-09-15 11:37:13    1649488 elife-3767122276026901222-fig1-figsupp1-v1.tif
2017-09-15 11:37:00     193218 elife-3767122276026901222-fig1-figsupp2-v1-download.jpg
2017-09-15 11:37:00     193218 elife-3767122276026901222-fig1-figsupp2-v1.jpg
2017-09-15 11:37:12     823684 elife-3767122276026901222-fig1-figsupp2-v1.tif
2017-09-15 11:37:00    1013365 elife-3767122276026901222-fig1-v1-download.jpg
2017-09-15 11:37:00    1013365 elife-3767122276026901222-fig1-v1.jpg
2017-09-15 11:37:12    3537508 elife-3767122276026901222-fig1-v1.tif
2017-09-15 11:37:01     116067 elife-3767122276026901222-fig2-figsupp1-v1-download.jpg
2017-09-15 11:37:01     116067 elife-3767122276026901222-fig2-figsupp1-v1.jpg
2017-09-15 11:37:11     126312 elife-3767122276026901222-fig2-figsupp1-v1.tif
2017-09-15 11:37:01     220869 elife-3767122276026901222-fig2-figsupp2-v1-download.jpg
2017-09-15 11:37:01     220869 elife-3767122276026901222-fig2-figsupp2-v1.jpg
2017-09-15 11:37:11     414720 elife-3767122276026901222-fig2-figsupp2-v1.tif
2017-09-15 11:37:02     593003 elife-3767122276026901222-fig2-v1-download.jpg
2017-09-15 11:37:02     593003 elife-3767122276026901222-fig2-v1.jpg
2017-09-15 11:37:11    2178536 elife-3767122276026901222-fig2-v1.tif
2017-09-15 11:37:03     602108 elife-3767122276026901222-fig3-v1-download.jpg
2017-09-15 11:37:03     602108 elife-3767122276026901222-fig3-v1.jpg
2017-09-15 11:37:09    2114332 elife-3767122276026901222-fig3-v1.tif
2017-09-15 11:37:04    1550969 elife-3767122276026901222-fig4-figsupp1-v1-download.jpg
2017-09-15 11:37:03    1550969 elife-3767122276026901222-fig4-figsupp1-v1.jpg
2017-09-15 11:37:10    7048808 elife-3767122276026901222-fig4-figsupp1-v1.tif
2017-09-15 11:37:04     343422 elife-3767122276026901222-fig4-v1-download.jpg
2017-09-15 11:37:04     343422 elife-3767122276026901222-fig4-v1.jpg
2017-09-15 11:37:09    1450492 elife-3767122276026901222-fig4-v1.tif
2017-09-15 11:37:05    1148634 elife-3767122276026901222-fig5-figsupp1-v1-download.jpg
2017-09-15 11:37:05    1148634 elife-3767122276026901222-fig5-figsupp1-v1.jpg
2017-09-15 11:37:10    5762936 elife-3767122276026901222-fig5-figsupp1-v1.tif
2017-09-15 11:37:06    1189822 elife-3767122276026901222-fig5-figsupp2-v1-download.jpg
2017-09-15 11:37:06    1189822 elife-3767122276026901222-fig5-figsupp2-v1.jpg
2017-09-15 11:37:11    6051204 elife-3767122276026901222-fig5-figsupp2-v1.tif
2017-09-15 11:37:06    1109303 elife-3767122276026901222-fig5-v1-download.jpg
2017-09-15 11:37:06    1109303 elife-3767122276026901222-fig5-v1.jpg
2017-09-15 11:37:09    5634848 elife-3767122276026901222-fig5-v1.tif
2017-09-15 11:37:07     410230 elife-3767122276026901222-fig6-v1-download.jpg
2017-09-15 11:37:07     410230 elife-3767122276026901222-fig6-v1.jpg
2017-09-15 11:37:09    1722972 elife-3767122276026901222-fig6-v1.tif
2017-09-15 11:37:07     592381 elife-3767122276026901222-fig7-v1-download.jpg
2017-09-15 11:37:07     592381 elife-3767122276026901222-fig7-v1.jpg
2017-09-15 11:37:12    3047296 elife-3767122276026901222-fig7-v1.tif
2017-09-15 11:37:08     335790 elife-3767122276026901222-fig8-v1-download.jpg
2017-09-15 11:37:08     335790 elife-3767122276026901222-fig8-v1.jpg
2017-09-15 11:37:12    1654516 elife-3767122276026901222-fig8-v1.tif
2017-09-15 11:37:39      22556 elife-3767122276026901222-inf1-v1.tif
2017-09-15 11:37:39      22976 elife-3767122276026901222-inf2-v1.tif
2017-09-15 11:37:39      24592 elife-3767122276026901222-inf3-v1.tif
2017-09-15 11:37:39      24088 elife-3767122276026901222-inf4-v1.tif
2017-09-15 11:37:39      22756 elife-3767122276026901222-inf5-v1.tif
2017-09-15 11:37:40      22952 elife-3767122276026901222-inf6-v1.tif
2017-09-15 11:37:40      22888 elife-3767122276026901222-inf7-v1.tif
2017-09-15 11:37:40      22300 elife-3767122276026901222-inf8-v1.tif
2017-09-15 11:37:40      22816 elife-3767122276026901222-inf9-v1.tif
```

**Pull request merged**
