### PR TITLE
Feature publish poa cleanup

### PR DESCRIPTION
**Pull request by gnott**
Changes done over a few months
* Code linting
* Activity PublishPOA is removed, now the PublishPOA workflow does PublishFinalPOA as its primary activity
* Removed old tests and FTP settings used by PublishPOA activity
* PublishFinalPOA new abilities: cleans the outbox, sends an email (like PublishPOA used to)
* PublishFinalPOA ability removed: no longer adds XML to outboxes, that is done elsewhere now (in ScheduleCrossref and ScheduleDownstream)
* Automated tests for PublishFinalPOA with a number of passing examples

### CODE REVIEW

**Comment by giorgiosironi** [comment]
I like the linting, how did you do it? Some cli tool or IDE?

**Comment by gnott** [comment]
Using ``pylint`` cli, basically by hand with its assistance of course.

The bulk of the linting in elife-bot was done a while ago, but this activity was left for last because I had a separate branch editing it.

**Comment by giorgiosironi** [comment]
Would you want to make it part of the build? These kind of changes are disruptive when done in large batches (giant diffs where only spaces are moved around), but very cheap if done frequently.

**Comment by gnott** [comment]
It doesn't need to be integrated as a step yet, in my opinion. Maybe at a later date if we have more stringent rules in place.

**Pull request merged**
