### PR TITLE
Elpp 1683 support for new Lax endpoint

### PR DESCRIPTION
**Pull request by Jenniferstrej**
@gnott 

Lax provider endpoint changes;
More unit tests to cover more 'failing' scenarios

### CODE REVIEW

**Comment by Jenniferstrej** [comment]
@gnott - Please check commit https://github.com/elifesciences/elife-bot/pull/333/commits/d395e4ec88738c6b3b4105b7f68fdd94f2d76d46 for changes in provider/article.py/check_is_article_published_by_lax

**Comment by gnott** [comment]
Looking good reading the code (although it's not very simple is it!).

1. I wonder when None is returned instead of data, and then functions that try to get len(data) will throw an exception. Maybe it should return an empty list instead?
https://github.com/Jenniferstrej/elife-bot/blob/d395e4ec88738c6b3b4105b7f68fdd94f2d76d46/provider/lax_provider.py#L15

2. Do we have a test where the lax response has no "published" value for the first version? We'd need an additional "lax_article_versions_response_data" in the test where there is only one version returned and it has no "published" value (it is still unpublished). I'm assuming that is what lax would respond back with if the version 1 is still unpublished?

The changes satisfy the original return values of these functions (getting the pub date, checking for if a VoR is published, etc.) so the activities that depend on these *should* work just the same - great work there!

**Comment by Jenniferstrej** [comment]
Regarding question number 2. I assumed we would not see versions that did not have a pub date. From Luke's comment http://jira.elifesciences.org:8080/browse/ELPP-1555?focusedCommentId=14190&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14190 "Lax and some other services will be aware of unpublished content and will be requiring authentication to receive unpublished content. If we don't give the bot an api key, you will only get the version history of published articles - articles with no pubdate will be excluded from the results."

**Comment by Jenniferstrej** [comment]
Question number one. I believe the case of having a response 200 and None as data isn't an expected option. View https://lax.elifesciences.org/api/docs/#!/v2/Article_Version_List_GET, open GET /api/v2/articles/{id}/versions and use an example of article 0001. It will return 200 but an empty list anyway. I am going to change the examples whose mocks are returning 404 or 500 to have None as data, but things won't change. Please let me know if I missed some case.

**Comment by gnott** [comment]
Q1 I see, I wasn't aware of how the unpublished v1 would be back from Lax, good detail!

Q2 I didn't notice all the checks on len(data) only happen when the status code is 200, makes my point irrelevant.

Thanks Jen!

**Comment by Jenniferstrej** [comment]
Conflicts solved. @giorgiosironi - I changed the title as this is no longer blocked. So we can merge it when you are ready.

**Pull request merged**
