### PR TITLE
It's time to deploy

### PR DESCRIPTION
**Pull request by Jenniferstrej**
Any objections?
@gnott ; @giorgiosironi

### CODE REVIEW

**Comment by giorgiosironi** [comment]
This is a large change and it's only becoming larger with time :+1:

**Comment by Jenniferstrej** [comment]
I am going on holiday on Friday and it would be good to have this live the whole day of tomorrow so then I can be of help in case there are any problems. @gnott, if you are happy you can trigger the build. 👍

**Comment by gnott** [comment]
Summary,

* new eif provider
* get update date of an article, received in the ingest or publish endpoint response
* add or change the update date in the EIF in new activity RewriteEIF
* new process provider
* processes do not have multiple threads anymore
* processes like worker and decider and others will be more gracefully shutdown when restarted
* ResizeImages writes source files to disk before resizing
* removed PostEIF activity
* removed ProcessXMLArticle workflow
* some various refactoring
* lots more automated test scenarios

**Comment by gnott** [comment]
Alfred was kind enough to deploy for me :+1:

**Comment by giorgiosironi** [comment]
`develop`, `approved`, and `master` are now aligned. Thanks :+1:

**Pull request merged**
