### PR TITLE
Use latest elifepubmed library.

### PR DESCRIPTION
**Pull request by gnott**
I noticed something with the new PubMed plain language summary, and I want to deploy this tiny tweak to add spaces between joined paragraphs.

### CODE REVIEW

**Comment by gnott** [comment]
Not a big rush, but something is weird with Alfred, if it is worth a look @lsh-0?

**Comment by lsh-0** [comment]
nuts, that was me. fixing.

**Comment by lsh-0** [comment]
PR: https://github.com/elifesciences/builder/pull/611

I'll see if I can fix the machine directly as it takes builder a little while to get through CI and deployed

**Comment by gnott** [comment]
I'd have to wait for `end2end` tests before deploying anyway, I can check back in a couple hours and deploy then if green - thanks @lsh-0!

**Comment by lsh-0** [comment]
kicking build ...

**Comment by lsh-0** [comment]
all green, sorry about that

I've updated end2end as well. prod looks fine

**Comment by gnott** [comment]
Thanks for the help @lsh-0!

**Pull request merged**
