### PR TITLE
Tweaks to tests for less warnings and errors. Can also remove the …

### PR DESCRIPTION
**Pull request by gnott**
…  .keepme file now too I think.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
The `.keepme` is there because Git does not keep track of empty directories, and the directory wasn't getting created by the tests setup. If you remove `tests/tmp/` manually, do the tests still run correctly?

**Comment by gnott** [comment]
The tests run ok for me and on travis-ci. Are you able to test elsewhere, or if anyone else finds it does not run.

**Comment by giorgiosironi** [comment]
I'll check out the branch on a builder VM, which should be very similar to CI.

**Comment by giorgiosironi** [comment]
Running this branch I get this error:
```
(venv) [15:21:14][elife@elife-bot-dev:/opt/elife-bot]$ ./project_tests.sh 
features/001_settings.feature

1 feature (1 passed)
8 scenarios (8 passed)
32 steps (32 passed)
features/002_boto.feature

1 feature (1 passed)
4 scenarios (4 passed)
34 steps (34 passed)
features/003_reqs.feature

1 feature (1 passed)
12 scenarios (12 passed)
36 steps (36 passed)
features/005_provider_simpleDB.feature

1 feature (1 passed)
42 scenarios (42 passed)
395 steps (395 passed)
features/006_provider_filesystem.feature


<Step: "When I write the document to tmp_dir with filesystem">
Traceback (most recent call last):
  File "/opt/elife-bot/venv/local/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
    ret = self.function(self.step, *args, **kw)
  File "/opt/elife-bot/tests/features/filesystem_steps.py", line 50, in i_write_the_document_to_tmp_dir_with_filesystem
    world.fs.write_document_to_tmp_dir(world.document)
  File "/opt/elife-bot/provider/filesystem.py", line 49, in write_document_to_tmp_dir
    f_write = self.open_file_from_tmp_dir(filename, "wb")
  File "/opt/elife-bot/provider/filesystem.py", line 119, in open_file_from_tmp_dir
    self.make_tmp_dir()
  File "/opt/elife-bot/provider/filesystem.py", line 203, in make_tmp_dir
    raise e
OSError: [Errno 2] No such file or directory: 'tmp/2016-06-27.15.22.26.filesystem_unzip'

1 feature (0 passed)
1 scenario (0 passed)
9 steps (1 failed, 2 skipped, 6 passed)

List of failed scenarios:
  Scenario Outline: Unzip a file to find multiple files inside   # features/006_provider_filesystem.feature:6
```

It seems I have a missing prefix or something similar, because the path should either be `/tmp` or `tests/tmp`. Will debug it tomorrow.

**Comment by gnott** [comment]
I rarely run the lettuce tests, so there could be something there.

The reason I removed the .keepme file was one of the tests now deletes all files from the tests/tmp dir, so it ends up getting deleted when running tests. Then when committing via git, the deleted file shows up as being deleted. If we can get away with no .keepme, then we do not need to modify how the test deletes files from /tests/tmp

**Comment by Jenniferstrej** [comment]
Oh! Yes, my tests delete the contents of the tmp folder. I've been running
my tests and creating the folders at runtime, except tmp. I need to review
that then and not delete the .keepme in the tmp since it is used across
different tests.

On 27 June 2016 at 16:36, Graham Nott <notifications@github.com> wrote:

> I rarely run the lettuce tests, so there could be something there.
>
> The reason I removed the .keepme file was one of the tests now deletes all
> files from the tests/tmp dir, so it ends up getting deleted when running
> tests. Then when committing via git, the deleted file shows up as being
> deleted. If we can get away with no .keepme, then we do not need to modify
> how the test deletes files from /tests/tmp
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/elifesciences/elife-bot/pull/258#issuecomment-228783235>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AC4pPnZVNJ5zWMXmbW3JEBFIx0K2RU5dks5qP-3ugaJpZM4I-J3c>
> .
>



-- 
Jennifer

**Comment by giorgiosironi** [comment]
Either not removing the `.keepme` or create the `tmp/` folder on demand - the important thing is that if we check out the code on a clean builder instance both `lettuce` and `unittest` run. I can test that for you.

**Comment by gnott** [comment]
Only one change remains that I'd like to get in, I will open a new PR for that.

**Pull request closed without merging**
