### PR TITLE
New PoA libraries

### PR DESCRIPTION
**Pull request by gnott**
Fixes https://github.com/elifesciences/elife-poa-xml-generation/issues/299

 I am opening a PR for review when it is possible. It is working, and uses the new PoA libraries in their most recent form (one of the sha points to branches waiting to be merged).

Basically, many changes in the ``PackagePOA`` activity to use the new PoA libraries instead of ``elife-poa-xml-generation``.

There are some other changes included here done along the way, including
* Moved some doi and volume function to the ``utils.py`` provider
* New config files shown in the ``settings-example.py``
* Changed the FakeStorageContext in two ways: 1. to make it easy to override the directory it loads data from, and 2. change how it reads the files which was previously incompatible when reading zip files (on Windows only, perhaps)
* A small fix to the PubMed deposit tests that was leaving temporary files on disk
* Removed the PackagePOA lettuce tests
* Added CSV files with their original names, starting with "ejp_query_tool_query_id_ ...", in order to test downloading CSV files from the storage provider
* Updated the ``poa_funding.csv`` and ``poa_manuscript.csv`` test fixtures to reflect the current data format in use now
* Some code linting

Changes planned for a later PR is to remove all the code required for the old ``elife-poa-xml-generation`` library once it is no longer required.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Have the duty to cover this in end2end, by triggering manually the workflow that this activity is involved in. Doing a spike now.

**Comment by gnott** [comment]
I was to open a JIRA ticket to discuss end2end tests I think, I haven't done that yet. I can provide some details and files to structure an end2end test if it is unclear.

**Comment by gnott** [comment]
Adding end2end details to https://elifesciences.atlassian.net/browse/ELPP-1599

**Comment by gnott** [comment]
I did local manual test and I'm fairly sure the libraries and the logic are functioning. Yesterday, I resolved a merge conflict with the develop branch. To avoid having this PR to live too long, I will go through the motions to deploy this. Sorry to not wait for end2end tests, but we've survived without them so far, and it can relieve the pressure on having to compose them I hope.

**Comment by giorgiosironi** [comment]
> Sorry to not wait for end2end tests

There was definitely no time to cover the whole PoA flow at the time, and arguably we will have to dedicate more focus to the digests coverage. I plan to try to finish running the first workflow for the PoA tests, then start covering digests instead.

**Pull request merged**
