### PR TITLE
Removed those 2 lettuce tests since I have removed those functions fr…

### PR DESCRIPTION
**Pull request by Jenniferstrej**
…om Expand Article and put them inside providers/article_structure.py

### CODE REVIEW

**Comment by gnott** [comment]
I think tests/features/060_activity_ExpandArticle.feature uses those functions. Those tests show as undefined now not failing per se. 

We can probably delete this ExpandArticle lettuce test since it is probably well covered in the other test scenarios.

**Comment by Jenniferstrej** [comment]
Yes. Ive just created another PR where I delete The definition of the
lettuce tests and add unit tests that do the same, bit for the correct
class

**Comment by Jenniferstrej** [comment]
If you are ok with it you can merge this PR (fixes failure on develop
Jenkins)

**Comment by Jenniferstrej** [comment]
Forgot to send the link https://github.com/elifesciences/elife-bot/pull/294

**Comment by gnott** [comment]
That's great, I was thinking a separate provider test for article_structure and you've done it!

**Pull request merged**
