### PR TITLE
Displays article_id in log on error

### PR DESCRIPTION
**Pull request by Jenniferstrej**

### CODE REVIEW

**Comment by Jenniferstrej** [comment]
@jhroot , @giorgiosironi - anything further to log on the error level?

**Comment by giorgiosironi** [comment]
Since we are in the error case, I would try to log the bodies of request and response (unless they are megabytes in size)

**Comment by Jenniferstrej** [comment]
The bodies I believe will be too big, but the response I can add. Perhaps
the first 100 characters of the body? (just a suggestion)

On 8 July 2016 at 10:49, Giorgio Sironi <notifications@github.com> wrote:

> Since we are in the error case, I would try to log the bodies of request
> and response (unless they are megabytes in size)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/elifesciences/elife-bot/pull/272#issuecomment-231320302>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AC4pPo3os44BjDJOUEmD-0irQ7kGsTWUks5qTh0vgaJpZM4JH2IL>
> .
>



-- 
Jennifer

**Comment by gnott** [comment]
I added to PostEIF a while ago for non-success responses,
``self.logger.error("Body:" + r.text)``
https://github.com/elifesciences/elife-bot/blob/develop/activity/activity_PostEIF.py#L137

That would print the JSON schema validation errors back from the website in the dashboard response.

**Comment by Jenniferstrej** [comment]
Ok, I can add that to the shim then.

On 8 July 2016 at 15:32, Graham Nott <notifications@github.com> wrote:

> I added to PostEIF a while ago for non-success responses,
> self.logger.error("Body:" + r.text)
>
> https://github.com/elifesciences/elife-bot/blob/develop/activity/activity_PostEIF.py#L137
>
> That would print the JSON schema validation errors back from the website
> in the dashboard response.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/elifesciences/elife-bot/pull/272#issuecomment-231375283>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AC4pPjNUIIM9p3MveegpKQP2zX0botqeks5qTl91gaJpZM4JH2IL>
> .
>



-- 
Jennifer

**Comment by giorgiosironi** [comment]
:+1: for me

**Comment by Jenniferstrej** [comment]
@giorgiosironi gave 👍 and travis checks have passed. If there are no objections I will merge this into develop in the next few minutes.

**Comment by gnott** [comment]
:+1:

**Pull request merged**
