### PR TITLE
PLEASE DO NOT MERGE - Elpp 1297 (and 1298)

### PR DESCRIPTION
**Pull request by Jenniferstrej**
In order to be able to merge this code I first need to:
- Push "Consider Lax" flag support
- Change econ-tools to support workflow name parameter
- code review from @gnott at least (@jhroot and @giorgiosironi if you think it's pertinent)

@gnott : Please take a look at ScheduleDownstream as I  am now adding the settings prefix to the poa_packaging_bucket name. In production it's always empty but for testing purposes it's important since in a local environment we use our own prefixes. It shouldn't make any difference but just in case you have a prefix set in your test environment.

@gnott , @giorgiosironi : Since we also have new workflow/activity names in place, I needed to register them locally. How is it normally done in end2end and production? When is register.py run?

### CODE REVIEW

**Comment by giorgiosironi** [comment]
`register.py` is run at each deploy, against the environment that the current machine is configured to use: https://github.com/elifesciences/elife-bot-formula/blob/master/salt/elife-bot/init.sls#L218

**Comment by giorgiosironi** [comment]
The build first failed on Alfred due to a timeout from `bitbucket.org` (don't ask), but after rerunning it, the output was:
```
15:32:55 [54.89.151.253] out: features/001_settings.feature
15:32:55 [54.89.151.253] out: Traceback (most recent call last):
15:32:55 [54.89.151.253] out:   File "/opt/elife-bot/venv/bin/lettuce", line 11, in <module>
15:32:55 [54.89.151.253] out:     sys.exit(main())
15:32:55 [54.89.151.253] out:   File "/opt/elife-bot/venv/local/lib/python2.7/site-packages/lettuce/bin.py", line 120, in main
15:32:55 [54.89.151.253] out:     result = runner.run()
15:32:55 [54.89.151.253] out:   File "/opt/elife-bot/venv/local/lib/python2.7/site-packages/lettuce/__init__.py", line 163, in run
15:32:55 [54.89.151.253] out:     self.loader.find_and_load_step_definitions()
15:32:55 [54.89.151.253] out:   File "/opt/elife-bot/venv/local/lib/python2.7/site-packages/lettuce/fs.py", line 50, in find_and_load_step_definitions
15:32:55 [54.89.151.253] out:     module = __import__(to_load)
15:32:55 [54.89.151.253] out:   File "/opt/elife-bot/tests/features/article_steps.py", line 7, in <module>
15:32:55 [54.89.151.253] out:     import provider.article as articlelib
15:32:55 [54.89.151.253] out:   File "/opt/elife-bot/provider/article.py", line 14, in <module>
15:32:55 [54.89.151.253] out:     import lax_provider
15:32:55 [54.89.151.253] out:   File "/opt/elife-bot/provider/lax_provider.py", line 3, in <module>
15:32:55 [54.89.151.253] out:     from article import article
15:32:55 [54.89.151.253] out: ImportError: cannot import name article
```

**Comment by gnott** [comment]
``features/001_settings.feature`` would be failed lettuce tests. I can debug that when it is important, and also their days are numbered anyway.

**Comment by giorgiosironi** [comment]
The possible outcomes of Lettuce failures are:
1. the test is not useful anymore, it is removed
2. the test is maintained and brought back to green
I'll welcome substitute tests using the standard `unittest` framework.

**Comment by Jenniferstrej** [comment]
Thanks @giorgiosironi , I'll take a look at the lettuce tests and push the latest changes for lax flagging.

**Comment by gnott** [comment]
I tested and tried this to get the lettuce tests to run https://github.com/elifesciences/elife-bot/pull/317  although I think there could be a bug with the other tests. I also got a failure running them locally.

**Pull request merged**
