### PR TITLE
Elife tools 2 0 xml branch refreshed

### PR DESCRIPTION
**Pull request by gnott**
The elifetools parser on this branch gets updated here - it was too old and looking at journal pages they were not reflecting what we have today.

I also merged master into this - I hope that is ok for deploying on continuumtest.

@giorgiosironi are you able to please confirm merging these features are ok, and are there any other steps you must do to get this into the continuumtest environment?

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Once this is merged (I will do so now), a `./bldr update` command needs to be run to get the new version on `elife-bot--continuumtest`. Otherwise it will get that version in the following 24 hours with the daily update. Will do it immediately

**Comment by giorgiosironi** [comment]
Instance should now be up to date.

**Comment by gnott** [comment]
Thanks @giorgiosironi - I'm not sure this made the change I had hoped though, slightly unrelated. What version of elifetools does the continuumtest lax instance use? That seems to be where it is not reproducing the output I generate locally.

**Comment by giorgiosironi** [comment]
Dumping what I can find:
```
elife@ip-10-0-2-111:/opt/elife-bot$ git log | head
commit 8ddd7f290e3058e04f0159018f442d5c51454ec0
Merge: 347c6bd e82aef3
Author: Giorgio Sironi <info@giorgiosironi.com>
Date:   Tue Apr 18 11:46:43 2017 +0100

    Merge pull request #438 from gnott/elife_tools_2_0_xml
    
    Elife tools 2 0 xml branch refreshed

commit e82aef399ae81c1c530912e10edff95aee393b34
elife@ip-10-0-2-111:/opt/elife-bot$ cat requirements.txt | grep elifetools
git+https://github.com/elifesciences/elife-tools.git@d95f3854e4925e23cf715a9461c9211499bdfaa3#egg=elifetools
```
which is the latest `develop` branch. Is that what you want?

**Comment by giorgiosironi** [comment]
However, I'm not sure https://github.com/elifesciences/elife-bot-formula/blob/master/salt/elife-bot/init.sls#L41 correctly changes the commit of a pip dependency, I have seen this problem before:
https://github.com/elifesciences/bot-lax-adaptor/blob/develop/install.sh#L17

**Comment by giorgiosironi** [comment]
I upgraded elifetools manually there, I will substitute the state in the formula with a more thorough install.sh script like for bot-lax-adaptor.

**Comment by gnott** [comment]
develop branch will be good. I'm just trying to explain why the lax data is not what it should be. I'll try another feed of the article to test.

**Comment by giorgiosironi** [comment]
To be clear, it was supposed to have the latest `develop`, but the formula wasn't updating it correctly, so it was some older version (no easy way to know which). Know I have updated it manually and I am working on fixing the automation.

**Comment by giorgiosironi** [comment]
I'll run also a new Salt highstate now to restart all processes which may have old code.

**Comment by giorgiosironi** [comment]
Salt highstate updated successfully, all processes should have the latest code now.

**Comment by giorgiosironi** [comment]
https://github.com/elifesciences/elife-bot/pull/439 to fix this in the future

**Comment by gnott** [comment]
I think this is slightly off-topic and we can move the discussion elsewhere if you want. It still seems to be a mismatch.

http://continuumtest--lax.elifesciences.org/api/v2/articles/666/versions/8  should include a paragraph with the text "Genus: Leishmania. There are 3 subgenus of Leishmania:".

I believe this would be just on the lax instance. If it is using the develop branch of elifetools, then I don't think it is up to date (at least I don't have a good alternately explanation).

**Comment by giorgiosironi** [comment]
```
elife@continuumtest--lax:/opt/bot-lax-adaptor$ cat requirements.txt | grep elifetools
git+https://github.com/elifesciences/elife-tools.git@2561b181ad2552a9c57f69dafed006e1cf6b082f#egg=elifetools
```
According to https://github.com/elifesciences/elife-tools/commits/develop it's 4 commits behind `elifetools@develop`. I'll add an update build that proposes the update to the latest version as a PR like we do with other projects.

**Comment by giorgiosironi** [comment]
See https://github.com/elifesciences/bot-lax-adaptor/pull/173 and https://ci--alfred.elifesciences.org/job/dependencies-bot-lax-adaptor-update-elife-tools/

**Comment by gnott** [comment]
Only four commits behind would not explain it too well. Is it possible the elifetools isn't updating when pip install -r requirements.txt is called on lax?

**Comment by giorgiosironi** [comment]
Yes, I'll fix this with https://github.com/elifesciences/elife-bot/pull/439

**Pull request merged**
