### PR TITLE
Retry on SSL timeout from Github

### PR DESCRIPTION
**Pull request by giorgiosironi**
Also:
- Using storage_provider for S3 access
- Stop reading the file to a tmp file that is subsequently ignored
- Linter rightly complains that instantiating a class should not return a different class

### CODE REVIEW

**Comment by Jenniferstrej** [comment]
👍

**Comment by gnott** [comment]
Is there a test for UpdateRepository that passes? Or at least to know whether the storage provider is working as expected? I'm curious with the large try except block whether it all gets covered by the test case.

**Comment by giorgiosironi** [comment]
The test only covers the new case (temporary failure) but I'll expand it with a couple of happy paths then. Expect a new `github` provider module then...

**Comment by giorgiosironi** [comment]
We have been plagued by Github failures during end2end runs, so I'll update this to get it merged.

**Comment by giorgiosironi** [comment]
Implementation changed because the storage provider has been introduced separately. Closing and opening a new PR.

**Pull request closed without merging**
