### PR TITLE
Processes streamlining

### PR DESCRIPTION
**Pull request by giorgiosironi**
We can now remove a lot of code related to multiprocessing, since that is managed by the Upstart configuration.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Rebased to resolve conflicts.

**Comment by Jenniferstrej** [comment]
👍

**Comment by giorgiosironi** [comment]
Long story short: due to timeouts of precisely 5 minutes in the end2end tests, I discovered that we need to shutdown the workers in a cleaner way if we want to avoid activities being assigned to dead workers:
http://docs.aws.amazon.com/java-sdk/latest/developer-guide/swf-graceful-shutdown.html
If there are no blockers to this PR, tomorrow I'll merge and test it in end2end, to then build upon `monitor_interrupt` and intercept the SIGTERM.

**Comment by giorgiosironi** [comment]
As discussed on Slack/email, going for this and building graceful shutdown on top to avoid 15-minute timeouts of activities after deploys.

**Pull request merged**
